[package]
name = "snow-shot-tauri-commands-ocr"
version = "0.1.0"
edition = "2024"

[dependencies]
tauri = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
image = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
base64 = { workspace = true }
sha2 = "0.10"
hmac = "0.12"
hex = "0.4"
chrono = { version = "0.4", features = ["clock"] }

snow-shot-app-services = { workspace = true }

paddle-ocr-rs = "0.6.0"

[target.'cfg(any(target_os = "windows"))'.dependencies]
snow-shot-webview = { workspace = true }
