[package]
name = "snow-shot-tauri-commands-screenshot"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { workspace = true }
tauri = { workspace = true }
tokio = { workspace = true }
xcap = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }

snow-shot-app-shared = { workspace = true }
snow-shot-app-os = { workspace = true }
snow-shot-app-utils = { workspace = true }
snow-shot-webview = { workspace = true }
snow-shot-global-state = { workspace = true }

[target.'cfg(any(target_os = "windows"))'.dependencies]
webview2-com = "0.39.0"
windows-core = { version = "0.62" }
windows = { workspace = true }
