[package]
name = "snow-shot-app-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
xcap = { workspace = true }
tauri = { workspace = true }
zune-jpegxl = { workspace = true }
zune-core = { workspace = true }
device_query = { workspace = true }
image = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
snow-shot-app-shared = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
base64 = { workspace = true }

[target.'cfg(any(target_os = "macos"))'.dependencies]
objc2 = { workspace = true }
macos-accessibility-client = { workspace = true }

[target.'cfg(any(target_os = "windows"))'.dependencies]
windows = { workspace = true, features = ["Win32_UI_Magnification", "Win32_UI_WindowsAndMessaging"] }
rayon = { workspace = true }
image = { workspace = true }
widestring = "1.2.0"
windows-capture = "2.0.0-alpha.7"
half = "2.6.0"
webview2-com = "0.39.0"
windows-core = { version = "0.62" }
snow-shot-webview = { workspace = true }
clipboard-win = { workspace = true }